server:
  port: 8080
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: fashionstore
          contentType: application/json
        event-out:
          destination: fashionstore
          contentType: application/json

feign:
  hystrix:
    enabled: true
    
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8082
  

api:
  url:
    # ProductServie 호출 주소
    product: http://localhost:8081    
    # PaymentServie 호출 주소
    payment: http://localhost:8085
    # DeliveryServie 호출 주소
    delivery: http://localhost:8083
  
  
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: fashionstore
          contentType: application/json
        event-out:
          destination: fashionstore
          contentType: application/json

# ProductServie 호출 주소
api:
  url:
    # ProductServie 호출 주소
    product: http://product:8080    
    # PaymentServie 호출 주소
    payment: http://payment:8080
    # DeliveryServie 호출 주소
    delivery: http://delivery:8080
